version: 2
jobs:
  orchestrator_tests:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-orch-dependencies-{{ checksum "orchestrator/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-orch-dependencies-
      - run: ./.circleci/orchestrator-tests.sh

      - save_cache:
          paths:
            - orchestrator/node_modules
          key: v1-orch-dependencies-{{ checksum "orchestrator/package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - orchestrator_tests
