version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./build/setup.sh

      # clean up run cache
      - run: rm -rf _terraform
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: aws help --version
      - run: ./build/test.sh
