version: 2
jobs:
  orchestrator-tests:
    docker:
      - image: circleci/node:11.13
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-orch-dependencies-{{ checksum "orchestrator/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-orch-dependencies-

      - run: cd orchestrator && npm install

      - save_cache:
          paths:
            - orchestrator/node_modules
          key: v1-orch-dependencies-{{ checksum "orchestrator/package.json" }}

      # run tests!
      - run: cd orchestrator && npm test
