version: "2.1"

services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana-volume:/var/lib/grafana
  tsdb:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-volume:/prometheus
    networks:
      orbs:
        ipv4_address: 192.168.199.100
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli --gasLimit 90000000000 --gasPrice 1 -a 10 -m "vanish junk genuine web seminar cook absurd royal ability series taste method identify elevator liquid"
    ports:
      - 8545:8545
    networks:
      orbs:
        ipv4_address: 192.168.199.6

  node1:
    image: orbs:export
    environment:
      ETHEREUM_ENDPOINT: http://ganache:8545/
    ports:
      - 7050:8080
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
      - ./_tmp/blocks/node1/:/usr/local/var/orbs/
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node1.json --log /opt/orbs/logs/node1.log
    sysctls:
      net.core.somaxconn: 25000
    networks:
      orbs:
        ipv4_address: 192.168.199.2

  node2:
    image: orbs:export
    environment:
      ETHEREUM_ENDPOINT: http://ganache:8545/
    ports:
      - 7051:8080
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
      - ./_tmp/blocks/node2/:/usr/local/var/orbs/
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node2.json --log /opt/orbs/logs/node2.log
    sysctls:
      net.core.somaxconn: 25000
    networks:
      orbs:
        ipv4_address: 192.168.199.3

  node3:
    image: orbs:export
    environment:
      ETHEREUM_ENDPOINT: http://ganache:8545/
    ports:
      - 7052:8080
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
      - ./_tmp/blocks/node3/:/usr/local/var/orbs/
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node3.json --log /opt/orbs/logs/node3.log
    sysctls:
      net.core.somaxconn: 25000
    networks:
      orbs:
        ipv4_address: 192.168.199.4

  node4:
    image: orbs:export
    environment:
      ETHEREUM_ENDPOINT: http://ganache:8545/
    ports:
      - 7053:8080
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
      - ./_tmp/blocks/node4/:/usr/local/var/orbs/
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node4.json --log /opt/orbs/logs/node4.log
    sysctls:
      net.core.somaxconn: 25000
    networks:
      orbs:
        ipv4_address: 192.168.199.5

  signer-node-1:
    image: orbs:signer
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
    command: /opt/orbs/orbs-signer --listen :7777 --config /opt/orbs/config/node1.json --config /opt/orbs/config/node1.keys.json
    networks:
      orbs:
        ipv4_address: 192.168.199.9

  signer-node-2:
    image: orbs:signer
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
    command: /opt/orbs/orbs-signer --listen :7777 --config /opt/orbs/config/node2.json --config /opt/orbs/config/node2.keys.json
    networks:
      orbs:
        ipv4_address: 192.168.199.10

  signer-node-3:
    image: orbs:signer
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
    command: /opt/orbs/orbs-signer --listen :7777 --config /opt/orbs/config/node3.json --config /opt/orbs/config/node3.keys.json
    networks:
      orbs:
        ipv4_address: 192.168.199.11

  signer-node-4:
    image: orbs:signer
    volumes:
      - ./_logs/:/opt/orbs/logs
      - ./$CONSENSUSALGO-config/:/opt/orbs/config
    command: /opt/orbs/orbs-signer --listen :7777 --config /opt/orbs/config/node4.json --config /opt/orbs/config/node4.keys.json
    networks:
      orbs:
        ipv4_address: 192.168.199.12

networks:
  orbs:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.199.0/24
