version: "2.1"

services:
  tsdb:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/prom-storage:/prometheus

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    volumes:
      - /home/ubuntu/grafana:/var/lib/grafana

  db:
    image: mongo:3.3
    ports:
      - 27017:27017
      - /home/ubuntu/mongo:/data/db

  mysql_db:
    image: percona:5.7
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/percona:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
