global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node1
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["35.161.123.97"]
        labels:
          machine: "node1"
          vchain: 2013
  - job_name: node2
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["35.167.243.123"]
        labels:
          machine: "node2"
          vchain: 2013
  - job_name: node3
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.35.218.240"]
        labels:
          machine: "node3"
          vchain: 2013
  - job_name: node4
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.42.4.94"]
        labels:
          machine: "node4"
          vchain: 2013
  - job_name: node5
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.26.26.163"]
        labels:
          machine: "node5"
          vchain: 2013

  - job_name: node1_v111
    metrics_path: "/vchains/2014/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["35.161.123.97"]
        labels:
          machine: "node1"
          vchain: 2014
  - job_name: node2_v111
    metrics_path: "/vchains/2014/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["35.167.243.123"]
        labels:
          machine: "node2"
          vchain: 2014
  - job_name: node3_v111
    metrics_path: "/vchains/2014/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.35.218.240"]
        labels:
          machine: "node3"
          vchain: 2014
  - job_name: node4
    metrics_path: "/vchains/2014/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.42.4.94"]
        labels:
          machine: "node4"
          vchain: 2014
  - job_name: node5
    metrics_path: "/vchains/2014/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.26.26.163"]
        labels:
          machine: "node5"
          vchain: 2014