global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node1
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["http://35.161.123.97/vchains/2013"]
        labels:
          machine: "node1"
          vchain: 2013
  - job_name: node2
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["http://35.167.243.123/vchains/2013"]
        labels:
          machine: "node2"
          vchain: 2013
  - job_name: node3
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["http://52.35.218.240/vchains/2013"]
        labels:
          machine: "node3"
          vchain: 2013
  - job_name: node4
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["http://52.42.4.94/vchains/2013"]
        labels:
          machine: "node4"
          vchain: 2013
  - job_name: node5
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["http://52.26.26.163/vchains/2013"]
        labels:
          machine: "node5"
          vchain: 2013