global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node1
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["52.204.239.242"]
        labels:
          machine: "node1"
          vchain: 2013
  - job_name: node2
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["3.228.184.70"]
        labels:
          machine: "node2"
          vchain: 2013
  - job_name: node3
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["3.231.52.24"]
        labels:
          machine: "node3"
          vchain: 2013
  - job_name: node4
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["18.189.176.243"]
        labels:
          machine: "node4"
          vchain: 2013
  - job_name: node5
    metrics_path: "/vchains/2013/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["18.189.102.184"]
        labels:
          machine: "node5"
          vchain: 2013
