global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: orbs-statsd-exporter
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets: ["statsd-exporter:9102"]
  - job_name: node1
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node1:8080"]
        labels:
          machine: "node1"
          vchain: 42
  - job_name: node2
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node2:8080"]
        labels:
          machine: "node2"
          vchain: 42
  - job_name: node3
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node3:8080"]
        labels:
          machine: "node3"
          vchain: 42
  - job_name: node4
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node4:8080"]
        labels:
          machine: "node4"
          vchain: 42
