global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: node1
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node1:8080"]
        labels:
          machine: "node1"
          vchain: 1000
  - job_name: node2
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node2:8080"]
        labels:
          machine: "node2"
          vchain: 1000
  - job_name: node3
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node3:8080"]
        labels:
          machine: "node3"
          vchain: 1000
  - job_name: node4
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics.prometheus"
    scheme: http
    static_configs:
      - targets: ["node4:8080"]
        labels:
          machine: "node4"
          vchain: 1000
