global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  #
  #
  - job_name: orbs-local-1-1000
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics.prometheus'
    scheme: http
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
        labels:
          machine: 'local1'
          vchain: 1000

  #
  #
  #
  - job_name: orbs-local-2-1000
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics.prometheus'
    scheme: http
    static_configs:
      - targets: [ '127.0.0.1:9091' ]
        labels:
          machine: 'local2'
          vchain: 1000

  #
  #
  #
  - job_name: orbs-local-3-1000
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics.prometheus'
    scheme: http
    static_configs:
      - targets: [ '127.0.0.1:9092' ]
        labels:
          machine: 'local3'
          vchain: 1000

  #
  #
  #
  - job_name: orbs-local-4-1000
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics.prometheus'
    scheme: http
    static_configs:
      - targets: [ '127.0.0.1:9093' ]
        labels:
          machine: 'local4'
          vchain: 1000

